version: '3.8'

services:

  backend:
    container_name: backend
    build:
      context: ./backend
    depends_on:
      - postgres
    ports:
      - "8080:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/projectDB
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - postgres-network

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - postgres-network

  postgres:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_DB: projectDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - postgres-network

#  pgadmin:
#    image: dpage/pgadmin4:latest
#    container_name: pgadmin
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#    ports:
#      - "8080:8081"
#    depends_on:
#      - postgres
#    networks:
#      - postgres-network

networks:
  postgres-network:
    driver: bridge
